beam:
  http:
    url: "https://lab.beam.pro/api/v1/"
    username: "matt"
    password: "welovenetworkz"
  auth:
    username: "BeamName"
    password: "BeamPass"
    channel: 0
minecraft:
  username: "minecraftName"
